name = 'gh-stats-cf-worker'
main = "src/index.ts"
compatibility_date = "2024-11-27"

[vars]
GITHUB_USERNAME = "M4ss1ck"

# Secrets (set via `wrangler secret put`):
# - GITHUB_TOKEN
# - GITHUB_USERNAME (if you prefer it as a secret)
